SELECT CITY, LEN(CITY) AS LEN
FROM (
    SELECT TOP 1 CITY
    FROM STATION
    ORDER BY LEN(CITY) ASC, CITY ASC
) AS Shortest

UNION

SELECT CITY, LEN(CITY) AS LEN
FROM (
    SELECT TOP 1 CITY
    FROM STATION
    ORDER BY LEN(CITY) DESC, CITY ASC
) AS Longest;
